### PR TITLE
Remove dependency on java.xml.bind for ease of use with jdk9 

### LINKED ISSUE #112: coveralls-maven-plugin fails on Java 9
Build fails with the following error running under Java 9, probably something to do with their new package restrictions:
```
[ERROR] Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report
 (default-cli) on project HikariCP: Execution default-cli of goal org.eluder.coveralls:coveralls-maven-
plugin:4.3.0:report failed: A required class was missing while executing 
org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report: javax/xml/bind/DatatypeConverter
```

### PR DESCRIPTION
**Pull request by sesuncedu**
This PR Fixes #112 . 
It's easier to add a dependency than make sure that the module gets added to MAVEN_OPTS.  

1. Add dependency on Apache Commons Codec for hex util
2. Commons codec to generate hex strings from digests.
3. Update commons-lang plug in to current version (just on principle )

Transfer of intellectual property rights and Disclaimer of liability:

1. Unless required by applicable law this  software is provided on an "AS IS" BASIS,  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

2. To the extent that any intellectual property rights may inhere in the  changes associated with this pull request, I herein assert that I am the owner  of any such rights, and hereby transfer any such rights to Tapio Rautonen.

### CODE REVIEW

**Comment by ansell** [comment]
The Travis failure seems to have been caused by a whitespace issue, caught by the checkstyle plugin:

https://travis-ci.org/trautonen/coveralls-maven-plugin/builds/250001068#L2268

**Comment by johnou** [comment]
@trautonen ping

File: src/main/java/org/eluder/coveralls/maven/plugin/util/Md5DigestInputStream.java [hunk 1]
```diff
@@ -39,6 +39,6 @@ public Md5DigestInputStream(final InputStream stream) throws NoSuchAlgorithmExce
     }
 
     public String getDigestHex() {
-        return DatatypeConverter.printHexBinary(getMessageDigest().digest());
+        return new String(Hex.encodeHex(getMessageDigest().digest(),false));
```
Comment (johnou) [inline src/main/java/org/eluder/coveralls/maven/plugin/util/Md5DigestInputStream.java]: @sesuncedu couldn't we use https://commons.apache.org/proper/commons-codec/apidocs/org/apache/commons/codec/binary/Hex.html#encodeHexString-byte:A- ?

Comment (johnou) [reply src/main/java/org/eluder/coveralls/maven/plugin/util/Md5DigestInputStream.java]: The reason for the failing ci is a missing space after the comma, using the encodeHexString method would be nicer though IMO.

Comment (johnou) [reply src/main/java/org/eluder/coveralls/maven/plugin/util/Md5DigestInputStream.java]: @sesuncedu ping

Comment (hwbllmnn) [inline src/main/java/org/eluder/coveralls/maven/plugin/util/Md5DigestInputStream.java]:
```suggestion
        return new String(Hex.encodeHex(getMessageDigest().digest(), false));
```
Can this be merged then?

**Comment by bautrey37** [comment]
@trautonen 
Can a new release be pushed to the maven repository? How can I access these new changes from my pom.xml file?
